// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTAMAvDT1b_d1xZUu8qihnGmukDfqKOn8',
    appId: '1:707193746787:web:f58c7e2ee87c5993e88f56',
    messagingSenderId: '707193746787',
    projectId: 'careconnect-1601c',
    authDomain: 'careconnect-1601c.firebaseapp.com',
    storageBucket: 'careconnect-1601c.firebasestorage.app',
    measurementId: 'G-DGSFLG3EBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbcKauavlOUy1D0w8NGNLxVe-Jd8LJ74',
    appId: '1:707193746787:android:87b8b5355154d60fe88f56',
    messagingSenderId: '707193746787',
    projectId: 'careconnect-1601c',
    storageBucket: 'careconnect-1601c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOLWmupZViKca7AGidm1mqf9MAeG7BfGs',
    appId: '1:707193746787:ios:1b0b877352841ef8e88f56',
    messagingSenderId: '707193746787',
    projectId: 'careconnect-1601c',
    storageBucket: 'careconnect-1601c.firebasestorage.app',
    iosBundleId: 'com.example.qq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOLWmupZViKca7AGidm1mqf9MAeG7BfGs',
    appId: '1:707193746787:ios:1b0b877352841ef8e88f56',
    messagingSenderId: '707193746787',
    projectId: 'careconnect-1601c',
    storageBucket: 'careconnect-1601c.firebasestorage.app',
    iosBundleId: 'com.example.qq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTAMAvDT1b_d1xZUu8qihnGmukDfqKOn8',
    appId: '1:707193746787:web:d69be0236feeba99e88f56',
    messagingSenderId: '707193746787',
    projectId: 'careconnect-1601c',
    authDomain: 'careconnect-1601c.firebaseapp.com',
    storageBucket: 'careconnect-1601c.firebasestorage.app',
    measurementId: 'G-W6BJX8ZD5M',
  );
}
